infer_cfgs:
  # The deepspeed configuration
  ds_cfgs: ds_z3_config.json
  vllm_cfgs: vllm_basic.json
  
default:
  # Evaluation configurations
  eval_cfgs:
    batch_size: 1
    # Seed for random number generator
    seed: 0
    # Output directory name
    output_dir: null
    # Num shot
    n_shot: 0
    # Evaluation method
    action: generation
  # Configuration for data
  data_cfgs:
    # Task name
    task: default
    # Task directory
    task_dir: lmms-lab/MME
    # Evaluation split
    split: test

  # Model configurations
  model_cfgs:
    model_id: llava-1.5-7b-hf
    # Pretrained model name or path
    model_name_or_path: /aifs4su/yaodong/models/llava/llava-1.5-7b-hf
    # Chat template
    chat_template: LLAVA
    # Whether to trust remote code
    trust_remote_code: True
    # The max token length
    max_length: 1024
    # The max new tokens for generation
    max_new_tokens: 512
