infer_cfgs:
  # The deepspeed configuration
  ds_cfgs: ds_z3_config.json
  vllm_cfgs: vllm_basic.json
  
default:
  # evaluation configurations
  eval_cfgs:
    # judge model, options: [gpt models]
    judge_model: gpt-4
    #openai api url
    openai_api_base_url: API_URL
    #openai api key
    openai_api_key: API_KEY
    # Output directory name
    output_dir: null
    # Num shot
    n_shot: 0
    # Use Chain of Thought
    cot: true
    # The number of choices
    num_choices: 1
  # Configuration for data
  data_cfgs:
    # Task name
    task: default
    # Task directory
    task_dir: /aifs4su/yaodong/donghai/benchmark_open_source_0731/MT-Bench
    # Evaluation split
    split: test

  # Model configurations
  model_cfgs:
    model_id: Qwen2-7B-Instruct
    # Pretrained model name or path
    model_name_or_path: /aifs4su/yaodong/models/Qwen2-7B-Instruct
    # Chat template
    chat_template: Qwen
    # The max token length
    model_max_length: 2048
