train_cfgs:
  # The deepspeed configuration
  ds_cfgs: ds_z3_config.json

default:
  # Evaluation configurations
  eval_cfgs:
    # Seed for random number generator
    seed: 0
    # Output directory name
    output_dir: null
    # Num shot
    n_shot: 5
    # Evaluation method
    action: logits
  # Configuration for data
  data_cfgs:
    # Task name
    task: gaokao
    # Task directory
    task_dir: null
    # Evaluation split
    split: dev
    # Candidate labels
    candidate_labels: ["A", "B", "C", "D"]

  # Model configurations
  model_cfgs:
    # Model ID
    model_id: Meta-Llama-3-8B
    # Pretrained model name or path
    model_name_or_path: meta-llama/Meta-Llama-3-8B
    # Whether to trust remote code
    trust_remote_code: True
    # The max token length
    max_length: 1024
    # The max new tokens for generation
    max_new_tokens: 512
