train_cfgs:
  # The deepspeed configuration
  ds_cfgs: ds_z3_config.json

default:
  # evaluation configurations
  eval_cfgs:
    # Seed for random number generator
    seed: 0
    # judge model, options: [gpt-4]
    judge_model: gpt-4
    # The number of choices
    num_choices: 1
    # Output directory name
    output_dir: null
  # Configuration for data
  data_cfgs:
    # Task name
    task: mt_bench
    # Task directory
    task_dir: null

  # Model configurations
  model_cfgs:
    # Model ID
    model_id: Llama-3-8B
    # Pretrained model name or path
    model_name_or_path: meta-llama/Meta-Llama-3-8B
    # Whether to trust remote code
    trust_remote_code: True
    # The max token length
    model_max_length: 4096
    # The max token length for generation
    max_new_token: 1024
